# Path to Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="agnoster"

# Plugins
plugins=(
    z
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# Load Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Autocompletion Optimization
autoload -Uz compinit && compinit -C

# Keybindings for history search
bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward
zstyle ':completion:*' menu select

# FZF Keybindings
bindkey -s '^T' 'fzf-file-widget\n'
bindkey -s '^R' 'fzf-history-widget\n'
bindkey -s '\ec' 'fzf-cd-widget\n'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Kubernetes Aliases
if command -v kubectl &>/dev/null; then
  alias k=kubectl
  alias kgp='kubectl get pods'
  alias kgs='kubectl get svc'
  alias kctx='kubectl config use-context'
  alias kns='kubectl config set-context --current --namespace'
  source <(kubectl completion zsh)
  compdef k=kubectl
fi

# Git Optimizations
export GIT_OPTIONAL_LOCKS=0
export DISABLE_UNTRACKED_FILES_DIRTY="true"

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lah'
alias grep='grep --color=auto'
alias df='df -h'
alias du='du -sh *'
alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gl='git log --oneline --graph --decorate --all'

# Starship Prompt (Load Last)
#eval "$(starship init zsh)"
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/kulbhushan/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
